<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Administrador.aspx.cs" Inherits="Prototipo.Vistas.Administrador.Administrador" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <style type="text/css">
        .auto-style3 {
            margin-left: 363px;
        }
        .auto-style4 {
            text-align: center;
        }
        .auto-style5 {
            background-color: #CCCCFF;
        }
        .auto-style6 {
            margin-left: 262px;
        }
        .auto-style7 {
            margin-left: 284px;
        }
        .auto-style8 {
            text-align: right;
        }
        .auto-style9 {
            margin-left: 0px;
        }
        .auto-style10 {
            margin-left: 80px;
        }
        .auto-style11 {
            margin-left: 495px;
        }
        .auto-style12 {
            font-size: large;
        }
        .auto-style13 {
            margin-left: 274px;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div class="auto-style4">
            <div class="auto-style8">

                <asp:Label ID="lblNombreUsuario" runat="server" Text=""></asp:Label>
                <asp:Button ID="btnCerrarSesion" runat="server" Text="Cerrar Sesion" click ="btnCerrarSesion_Click" OnClick="btnCerrarSesion_Click1"/>
                <br />

            </div>
            <asp:LinkButton ID="LinkButton1" runat="server" PostBackUrl="~/Vistas/Home/Home.aspx">HOME</asp:LinkButton>
&nbsp;&nbsp;&nbsp;
            <asp:LinkButton ID="LinkButton2" runat="server" PostBackUrl="~/Vistas/Carrito/Carrito.aspx">CARRITO</asp:LinkButton>
&nbsp;&nbsp;<asp:HyperLink ID="HyperLink1" runat="server" NavigateUrl="~/Vistas/Mi Cuenta/MiCuenta.aspx">MI CUENTA</asp:HyperLink>
            &nbsp;
            <asp:LinkButton ID="LinkButton3" runat="server" PostBackUrl="~/Vistas/Login/InicioSesion.aspx">LOGIN</asp:LinkButton>
&nbsp;&nbsp;&nbsp;
            <asp:LinkButton ID="LinkButton4" runat="server" PostBackUrl="~/Vistas/Login/CrearCuenta.aspx">REGISTRARSE</asp:LinkButton>
            <br />
            <br />
            <br />
            <asp:DropDownList ID="ddlAdmin" runat="server" AutoPostBack="True" OnSelectedIndexChanged="ddlAdmin_SelectedIndexChanged">
                <asp:ListItem Value="--Seleccionar--">--Seleccionar--</asp:ListItem>
                <asp:ListItem>Categorias</asp:ListItem>
                <asp:ListItem>Productos</asp:ListItem>
                <asp:ListItem>Facturas</asp:ListItem>
                <asp:ListItem>Usuarios</asp:ListItem>
            </asp:DropDownList>
            <br />
            <br />
            <asp:GridView ID="gvCategorias" runat="server" AllowPaging="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" CssClass="auto-style3" ForeColor="#333333" GridLines="None" OnPageIndexChanging="gvCategorias_PageIndexChanging" CellSpacing="2" OnRowCancelingEdit="gvCategorias_RowCancelingEdit" OnRowDeleting="gvCategorias_RowDeleting" OnRowEditing="gvCategorias_RowEditing" OnRowUpdating="gvCategorias_RowUpdating" Width="696px">
                <AlternatingRowStyle BackColor="White" />
                <Columns>
                    <asp:TemplateField HeaderText="ID-Categoria">
                        <EditItemTemplate>
                            <asp:Label ID="lbIdCatEDIT" runat="server" Text='<%# Bind("Id") %>'></asp:Label>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblIdCategoria" runat="server" Text='<%# Bind("Id") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="DESCRPCION">
                        <EditItemTemplate>
                            <asp:TextBox ID="txtEditDescArticulo" runat="server" Text='<%# Bind("Descripcion") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lbDescripcion" runat="server" Text='<%# Bind("Descripcion") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
                <EditRowStyle BackColor="#7C6F57" />
                <FooterStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#666666" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#E3EAEB" />
                <SelectedRowStyle BackColor="#C5BBAF" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#F8FAFA" />
                <SortedAscendingHeaderStyle BackColor="#246B61" />
                <SortedDescendingCellStyle BackColor="#D4DFE1" />
                <SortedDescendingHeaderStyle BackColor="#15524A" />
            </asp:GridView>
            <br />
            <br />
            <asp:TextBox ID="txtDescripcionCategoria" runat="server" Visible="False" Width="193px"></asp:TextBox>
            <asp:Button ID="btnAgregarCategoria" runat="server" OnClick="btnAgregarCategoria_Click" Text="Agregar" Visible="False" />
            <br />
            <asp:Label ID="lblAgregar" runat="server"></asp:Label>
            <br />
            <asp:Label ID="lblPreguntaConfirmacion" runat="server" Visible="False"></asp:Label>
            <br />
            <asp:Button ID="btnAceptar" runat="server" OnClick="btnAceptar_Click" Text="Aceptar" Visible="False" />
            <asp:Button ID="btnCancelar" runat="server" OnClick="btnCancelar_Click" Text="Cancelar" Visible="False" />
        </div>
        <p class="auto-style4">
            &nbsp;</p>
        <div class="auto-style4">
            <asp:TextBox ID="txtNombreProducto" runat="server" Width="200px"></asp:TextBox>
            <asp:Button ID="btnFiltrarNombreProducto" runat="server" OnClick="btnFiltrarNombreProducto_Click" Text="Filtrar" Width="100px" />
&nbsp;&nbsp;&nbsp;
            <asp:DropDownList ID="ddlCategorias" runat="server" AutoPostBack="True" OnSelectedIndexChanged="ddlCategorias_SelectedIndexChanged" Width="200px">
            </asp:DropDownList>
            <asp:Button ID="btnQuitarFiltrosProducto" runat="server" OnClick="btnQuitarFiltrosProducto_Click" Text="Quitar Filtros" />
            <br />
            <br />
            <asp:GridView ID="gvArticulos" runat="server" AllowPaging="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnPageIndexChanging="gvArticulos_PageIndexChanging" OnRowCancelingEdit="gvArticulos_RowCancelingEdit" OnRowDeleting="gvArticulos_RowDeleting" OnRowEditing="gvArticulos_RowEditing" OnRowUpdating="gvArticulos_RowUpdating" Width="890px" CssClass="auto-style6">
                <Columns>
                    <asp:TemplateField HeaderText="Numero de Articulo">
                        <EditItemTemplate>
                            <asp:Label ID="lblEditIdArtGrvArt" runat="server" Text='<%# Bind("Id") %>'></asp:Label>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblIdArticuloGRVArticulos" runat="server" Text='<%# Bind("Id") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Categoria">
                        <EditItemTemplate>
                            <asp:DropDownList ID="ddlETcategoriasGrvArticulos" runat="server" DataSourceID="sqlDDLidCat" DataTextField="Descripcion" DataValueField="Id" Width="150px">
                            </asp:DropDownList>
                            <asp:SqlDataSource ID="sqlDDLidCat" runat="server" ConnectionString="<%$ ConnectionStrings:Prog3_IntegradorConnectionString2 %>" SelectCommand="SELECT * FROM [Categoria]"></asp:SqlDataSource>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblCatDesGrvArticulos" runat="server" Text='<%# Bind("Descripcion") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Nombre de Articulo">
                        <EditItemTemplate>
                            <asp:TextBox ID="txtEditNombArtGrvArt" runat="server"></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblNombreArtGrvArt" runat="server" Text='<%# Bind("Nombre_Art") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Precio">
                        <EditItemTemplate>
                            <asp:TextBox ID="txtEditPrecioUniGrvArt" runat="server"></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblPrecioUniGrvArt" runat="server" Text='<%# Bind("PrecioUnitario") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Unidades En Stock">
                        <EditItemTemplate>
                            <asp:TextBox ID="txtStockArtgrvArt" runat="server"></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblStockArticuloGrvArt" runat="server" Text='<%# Bind("StockArticulo") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
            </asp:GridView>
            <br />
            <br />
            <asp:TextBox ID="txtDescripcionArticulo" runat="server" CssClass="auto-style5" Visible="False">Descripcion</asp:TextBox>
            &nbsp;&nbsp;&nbsp;
            <asp:TextBox ID="txtPrecioUnitario" runat="server" CssClass="auto-style5" Visible="False">Precio Unitario</asp:TextBox>
            &nbsp;&nbsp;&nbsp;
            <asp:TextBox ID="txtStock" runat="server" CssClass="auto-style5" Visible="False">Stock</asp:TextBox>
            &nbsp;&nbsp;&nbsp;
            <asp:TextBox ID="txtUrlImagen" runat="server" CssClass="auto-style5" Visible="False">Url Imagen</asp:TextBox>
            &nbsp;&nbsp;&nbsp;
            <asp:DropDownList ID="ddlCategoriasArticulo" runat="server">
            </asp:DropDownList>
            &nbsp;&nbsp;&nbsp;
            <asp:Button ID="btnAgregarArticulo" runat="server" OnClick="btnAgregarArticulo_Click" Text="Agregar" Visible="False" />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
        </div>
        <div class="auto-style4">
            <br />
            <br />
            <asp:TextBox ID="txtNombreUsuarioAdmin" runat="server" Width="164px"></asp:TextBox>
&nbsp;&nbsp;&nbsp;
            <asp:Button ID="btnFiltrarNombreUsuarioAdmin" runat="server" OnClick="btnFiltrarNombreUsuarioAdmin_Click" Text="Filtrar" Visible="False" Width="56px" />
&nbsp;&nbsp;&nbsp;
            <asp:Button ID="btnQuitarFiltrosAdmin" runat="server" OnClick="btnQuitarFiltrosAdmin_Click" Text="Quitar Filtros" />
            <br />
            <br />
            <asp:GridView ID="gvAdmin" runat="server" AllowPaging="True" AutoGenerateColumns="False" AutoGenerateEditButton="True" OnPageIndexChanging="GridView1_PageIndexChanging" OnRowCancelingEdit="gvAdmin_RowCancelingEdit" OnRowEditing="gvAdmin_RowEditing" OnRowUpdating="gvAdmin_RowUpdating" Width="894px" CssClass="auto-style7">
                <Columns>
                    <asp:TemplateField HeaderText="Dni">
                        <EditItemTemplate>
                            <asp:Label ID="lblDniEditGrvAdmin" runat="server" Text='<%# Bind("DniUsuario") %>'></asp:Label>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblDniGrvAdmin" runat="server" Text='<%# Bind("DniUsuario") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Nombre">
                        <EditItemTemplate>
                            <asp:Label ID="lblNombreGrvAdmin" runat="server" Text='<%# Bind("NombreUsuario") %>'></asp:Label>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblNombreUsuarioGrvAdmin" runat="server" Text='<%# Bind("NombreUsuario") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Apellido">
                        <EditItemTemplate>
                            <asp:Label ID="lblApellidoGvdAdmin" runat="server" Text='<%# Bind("ApellidoUsuario") %>'></asp:Label>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblApellidoGrvAdmin" runat="server" Text='<%# Bind("ApellidoUsuario") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Email">
                        <EditItemTemplate>
                            <asp:Label ID="gvdMailEditAdmin" runat="server" Text='<%# Bind("Mail") %>'></asp:Label>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblMailGvdAdmin" runat="server" Text='<%# Bind("Mail") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Direccion">
                        <EditItemTemplate>
                            <asp:Label ID="gvdDirecGrvAdmin" runat="server" Text='<%# Bind("DireccionUsuario") %>'></asp:Label>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="gvdDirecGrvAdmin" runat="server" Text='<%# Bind("DireccionUsuario") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Admin">
                        <EditItemTemplate>
                            <asp:CheckBox ID="cbRolUsuarioAdmin" runat="server" Checked='<%# Bind("Rol") %>' />
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblRolGrvAdmin" runat="server" Text='<%# Bind("Rol") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
            </asp:GridView>
            <br />
        </div>
        <div>
            <br />
            <br />
            <div class="auto-style10">
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;
                <asp:Label ID="lblComentario" runat="server" Visible="False"></asp:Label>
                <br />
                <br />
                <asp:Label ID="lblDesde" runat="server" Text="DESDE:" Visible="False"></asp:Label>
                <br />
                <asp:Calendar ID="Calendar1" runat="server" BackColor="White" BorderColor="Black" CssClass="auto-style9" DayNameFormat="Shortest" ForeColor="Black" Height="220px" NextPrevFormat="FullMonth" TitleFormat="Month" Visible="False" Width="400px"></asp:Calendar>
                <br />
                <asp:Label ID="lblHasta" runat="server" Text="HASTA:" Visible="False"></asp:Label>
                <br />
                <asp:Calendar ID="Calendar2" runat="server" BackColor="White" BorderColor="Black" DayNameFormat="Shortest" ForeColor="Black" Height="220px" NextPrevFormat="FullMonth" TitleFormat="Month" Visible="False" Width="400px" CssClass="auto-style9"></asp:Calendar>
                <br />
                <br />
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <asp:Button ID="btnFiltrar" runat="server" OnClick="btnFiltrar_Click" Text="Filtrar" Visible="False" />
&nbsp;&nbsp;&nbsp;
                <asp:Button ID="btnQuitarFiltros" runat="server" OnClick="btnQuitarFiltros_Click" Text="Quitar Filtros" Visible="False" />
&nbsp;&nbsp;&nbsp;
                <asp:Button ID="btnReporte" runat="server" OnClick="btnReporte_Click" Text="Mostrar Reporte" Visible="False" />
                <br />
                <br />
                <br />
                <div class="auto-style4">
                    <asp:GridView ID="gvFacturas" runat="server" AllowPaging="True" AutoGenerateColumns="False" AutoGenerateSelectButton="True" BorderWidth="3px" CellPadding="4" CellSpacing="2" OnPageIndexChanging="gvFacturas_PageIndexChanging" OnSelectedIndexChanging="gvFacturas_SelectedIndexChanging" PageSize="9" CssClass="auto-style13">
                        <Columns>
                            <asp:TemplateField HeaderText="Numero de factura">
                                <ItemTemplate>
                                    <asp:Label ID="lblIdFactura" runat="server" Text='<%# Bind("Id_Factura") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Dni Cliente">
                                <ItemTemplate>
                                    <asp:Label ID="lblDniUsuario" runat="server" Text='<%# Bind("Dni_Usuario") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Nombre Cliente">
                                <ItemTemplate>
                                    <asp:Label ID="lblNombreCliente" runat="server" Text='<%# Bind("NombreCliente") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Fecha">
                                <ItemTemplate>
                                    <asp:Label ID="lblFechaVenta" runat="server" Text='<%# Bind("Fecha_Venta") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Monto Final">
                                <ItemTemplate>
                                    <asp:Label ID="lblMontoFinal" runat="server" Text='<%# Bind("MontoFinal") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                        </Columns>
                    </asp:GridView>
                    <br />
                    <asp:Label ID="lblRecaudado" runat="server" Visible="False" CssClass="auto-style12"></asp:Label>
                    <br />
                    <asp:Label ID="lblProductoMasVendido" runat="server" Visible="False" CssClass="auto-style12"></asp:Label>
                    <br />
                    <asp:Label ID="lblCategoriaMasVendida" runat="server" Visible="False" CssClass="auto-style12"></asp:Label>
                    <br />
                    <asp:Label ID="lblMejorCliente" runat="server" Visible="False" CssClass="auto-style12"></asp:Label>
                </div>
            </div>
        </div>
        <div>
            <br />
            <asp:GridView ID="gvDetalleFactura" runat="server" AutoGenerateColumns="False" CssClass="auto-style11" Width="464px">
                <Columns>
                    <asp:TemplateField HeaderText="N° Orden">
                        <ItemTemplate>
                            <asp:Label ID="lblNumeroOrden" runat="server" Text='<%# Bind("NumOrden") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Id Articulo">
                        <ItemTemplate>
                            <asp:Label ID="lblIdArticulo" runat="server" Text='<%# Bind("Id_Articulo") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Descripcion">
                        <ItemTemplate>
                            <asp:Label ID="lblDescripcion" runat="server" Text='<%# Bind("DescripcionArticulo") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Cantidad ">
                        <ItemTemplate>
                            <asp:Label ID="lblCantidad" runat="server" Text='<%# Bind("Cantidad") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Precio">
                        <ItemTemplate>
                            <asp:Label ID="lblPrecio" runat="server" Text='<%# Bind("PrecioUnitario") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
            </asp:GridView>
        </div>
    </form>
</body>
</html>
