<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Carrito.aspx.cs" Inherits="Prototipo.Carrito" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <style type="text/css">
        .auto-style1 {
            text-align: center;
        }
        .auto-style2 {
            margin-left: 21px;
            background-color: #FFFFFF;
        }
        .auto-style3 {
            height: 82px;
        }
        .auto-style4 {
            height: 54px;
        }
        .auto-style5 {
            text-decoration: underline;
            color: #FF0000;
            font-size: large;
        }
        .auto-style6 {
            text-align: right;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div class="auto-style6">

            <asp:Label ID="lblNombreUsuario" runat="server" Visible="False"></asp:Label>
            <asp:Button ID="btnCerrarSesion" runat="server" OnClick="btnCerrarSesion_Click" Text="Cerrar Sesion" />
            <br />

        </div>
        <div class="auto-style1">
            <div>
                <asp:HyperLink ID="HyperLink1" runat="server" NavigateUrl="~/Vistas/Home/Home.aspx">HOME</asp:HyperLink>
&nbsp;&nbsp;&nbsp;
                <asp:HyperLink ID="HyperLink2" runat="server" NavigateUrl="~/Vistas/Carrito/Carrito.aspx">CARRITO</asp:HyperLink>
&nbsp;&nbsp;&nbsp;
                <asp:HyperLink ID="HyperLink3" runat="server" NavigateUrl="~/Vistas/Mi Cuenta/MiCuenta.aspx">MI CUENTA</asp:HyperLink>
&nbsp;&nbsp;&nbsp;
                <asp:HyperLink ID="HyperLink4" runat="server" NavigateUrl="~/Vistas/Login/InicioSesion.aspx">LOGIN</asp:HyperLink>
&nbsp;&nbsp;&nbsp;
                <asp:HyperLink ID="HyperLink5" runat="server" NavigateUrl="~/Vistas/Login/Registro.aspx">REGISTRARSE</asp:HyperLink>
            </div>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <br />
            <asp:Label ID="lblAvisoCuenta" runat="server" CssClass="auto-style5" Text="DEBE INICIAR SESION PARA ACCEDER AL CARRITO" Visible="False"></asp:Label>
            <br />
            <asp:Label ID="lbComentarios" runat="server"></asp:Label>
            <br />
            <asp:GridView ID="gvCarrito" runat="server" AllowPaging="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" CellSpacing="2" CssClass="auto-style2" PageSize="15" Width="700px" BorderColor="#999999" BorderStyle="Solid" BorderWidth="3px" ForeColor="Black" OnDataBound="gvCarrito_DataBound" OnPageIndexChanging="gvCarrito_PageIndexChanging" OnRowCancelingEdit="gvCarrito_RowCancelingEdit" OnRowDeleting="gvCarrito_RowDeleting" OnRowEditing="gvCarrito_RowEditing" OnRowUpdating="gvCarrito_RowUpdating">
                <Columns>
                    <asp:TemplateField HeaderText="Nombre Producto">
                        <EditItemTemplate>
                            <asp:Label ID="lblNombreArticuloEdit" runat="server" Text='<%# Bind("descripcionArticulo") %>'></asp:Label>
                            <br />
                            <asp:Label ID="lblIdArticuloEdit" runat="server" Text='<%# Bind("id_articulo") %>' Visible="False"></asp:Label>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblNombreProducto" runat="server" Text='<%# Bind("descripcionArticulo") %>'></asp:Label>
                            <br />
                            <asp:Label ID="lblIdArticulo" runat="server" Text='<%# Bind("id_articulo") %>' Visible="False"></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Precio">
                        <EditItemTemplate>
                            <asp:Label ID="lblPrecioUnitarioEdit" runat="server" Text='<%# Bind("PrecioUnitario") %>'></asp:Label>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblPrecioUnitario" runat="server" Text='<%# Bind("PrecioUnitario") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Cantidad">
                        <EditItemTemplate>
                            <asp:TextBox ID="txtCantidad" runat="server" TextMode="Number"></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblCantidad" runat="server" Text='<%# Bind("cantidad") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Total">
                        <EditItemTemplate>
                            <asp:Label ID="lblPrecioTotalFila" runat="server" Text='<%# Bind("Total") %>'></asp:Label>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblPrecioTotalFila" runat="server" Text='<%# Bind("Total") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
            </asp:GridView>
            <br />
            <div class="auto-style3">
                <asp:Label ID="lblPreguntaConfirmacionEliminarProducto" runat="server" ForeColor="Red" Visible="False">¿ESTÁ SEGURO DE ELIMINAR PRODUCTO?</asp:Label>
                <br />
                <asp:Button ID="btnAceparEliminarProducto" runat="server" Text="Aceptar" OnClick="btnAceparEliminarProducto_Click" Visible="False" />
                <asp:Button ID="btnCancelarEliminarProducto" runat="server" Text="Cancelar" OnClick="btnCancelarEliminarProducto_Click" Visible="False" />
                <br />
                <asp:Button ID="btnFinalizarCompra" runat="server" Text="Confirmar Compra" Width="142px" OnClick="btnFinalizarCompra_Click" />
            </div>
            <div class="auto-style4">
                <asp:Label ID="lblConfirmacionDeCompra" runat="server" ForeColor="Red" Visible="False">CONFIRMAR COMPRA</asp:Label>
                <br />
                <asp:Button ID="btnConfirmarCompra" runat="server" Text="Confirmar " OnClick="btnConfirmarCompra_Click" Visible="False" />
                <asp:Button ID="btnCancelarConfirmarCompra" runat="server" Text="Cancelar" OnClick="btnCancelarConfirmarCompra_Click" Visible="False" />
            </div>
            <br />
            <br />
            <br />
            <br />
        </div>
    </form>
</body>
</html>
